### ISSUE TITLE
fit8那个项目，library怎么删了gradle脚本，，

### ISSUE THREAD

**Issue by jp1017** [steven2947/steven2947.github.io#1]
https://github.com/hongyangAndroid/FitAndroid7/blob/master/librararyforfileprovdider/build.gradle

**Comment by steven2947** [comment]
我是直接在fit7上修改,原来项目的那个作者停止更新了,所以不相关的我都清了

**Comment by jp1017** [comment]
删了会编译不过的 :smile:
